services:
  api:
    networks:
      edge:
        aliases: [blastjax-api]
  web:
    networks:
      edge:
        aliases: [blastjax-web]
  caddy:
    profiles: [standalone]

networks:
  edge:
    external: true
