"""The PostgreSQL schema this application expects.

This is the single source of truth for the shape of the database. Startup
verifies it (``db.init_schema``) and ``create_all`` builds it, both reading
the definitions below, so the check and the thing being checked cannot
describe two different schemas.

It used to live inside a SQLite-to-Postgres migration script. That script is
gone -- the app has been Postgres-only for a while, and keeping the DDL inside
a one-way importer meant the only copy of the schema was in a file nobody
could run any more.

``backend/test_core.py`` checks these definitions against the columns the
query layer actually selects.
"""

from __future__ import annotations

from typing import Any


SCHEMA: list[tuple[str, str]] = [
    (
        "_app_meta",
        """
        key   TEXT PRIMARY KEY,
        value TEXT
        """,
    ),
    (
        "app_user",
        """
        id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username      TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        is_superuser  BOOLEAN NOT NULL DEFAULT false,
        allowed_pages TEXT,
        created_at    TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(username)) > 0)
        """,
    ),
    (
        "blood_pressure",
        """
        id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        systolic    INTEGER,
        diastolic   INTEGER,
        pulse       INTEGER,
        spo2        INTEGER,
        temperature NUMERIC(5, 2),
        weight      NUMERIC(6, 2),
        notes       TEXT,
        created_at  TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "calendar_day_override",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        day        DATE UNIQUE,
        amount     DOUBLE PRECISION,
        created_at TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "credit_card",
        """
        id                     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                   TEXT,
        credit_limit           DOUBLE PRECISION,
        last_statement_balance DOUBLE PRECISION DEFAULT 0,
        current_balance        DOUBLE PRECISION DEFAULT 0,
        minimum_due            DOUBLE PRECISION DEFAULT 0,
        interest_rate          DOUBLE PRECISION DEFAULT 3.5,
        statement_date         DATE,
        due_date               DATE,
        created_at             TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "credit_card_payment",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        credit_card_id INTEGER,
        amount         DOUBLE PRECISION,
        payment_date   DATE,
        note           TEXT,
        created_at     TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "fixed_expense",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        period_half  INTEGER,
        period_year  INTEGER,
        period_month INTEGER,
        amount       DOUBLE PRECISION,
        description  TEXT,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "house_payment",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name       TEXT,
        notes      TEXT,
        created_at TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "house_payment_entry",
        """
        id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        house_payment_id INTEGER,
        paid_on          DATE,
        amount           DOUBLE PRECISION,
        created_at       TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "installment",
        """
        id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                TEXT,
        installment_current INTEGER,
        installment_total   INTEGER,
        principal           DOUBLE PRECISION,
        interest            DOUBLE PRECISION,
        payment_total       DOUBLE PRECISION,
        start_date          DATE,
        finish_date         DATE,
        remaining           DOUBLE PRECISION,
        original_total      DOUBLE PRECISION,
        credit_card_id      INTEGER,
        created_at          TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "installment_line",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        installment_id INTEGER,
        seq            INTEGER,
        principal      DOUBLE PRECISION DEFAULT 0,
        interest       DOUBLE PRECISION,
        payment_total  DOUBLE PRECISION,
        UNIQUE (installment_id, seq)
        """,
    ),
    (
        "lotto_game",
        """
        id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL UNIQUE
        """,
    ),
    (
        "lotto_draw",
        """
        id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        -- Unique per game, not globally: different games can draw on the
        -- same calendar date.
        draw_date     DATE NOT NULL,
        -- lotto_game.id; defaults to Ultra Lotto 6/58, the game tracked
        -- before lotto_game existed (see SEED_LOTTO_GAMES).
        game_id       INTEGER NOT NULL DEFAULT 3,
        n1            INTEGER,
        n2            INTEGER,
        n3            INTEGER,
        n4            INTEGER,
        n5            INTEGER,
        n6            INTEGER,
        created_at    TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        jackpot_prize DOUBLE PRECISION,
        winners       INTEGER NOT NULL DEFAULT 0,
        UNIQUE (draw_date, game_id),
        CHECK (
            (n1 IS NULL AND n2 IS NULL AND n3 IS NULL AND n4 IS NULL AND n5 IS NULL AND n6 IS NULL)
            OR (n1 >= 1 AND n1 < n2 AND n2 < n3 AND n3 < n4 AND n4 < n5 AND n5 < n6 AND n6 <= 58)
        )
        """,
    ),
    (
        "lotto_attempt",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        draw_id    INTEGER NOT NULL,
        n1         INTEGER NOT NULL,
        n2         INTEGER NOT NULL,
        n3         INTEGER NOT NULL,
        n4         INTEGER NOT NULL,
        n5         INTEGER NOT NULL,
        n6         INTEGER NOT NULL,
        created_at TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ticket     INTEGER,
        CHECK (n1 >= 1 AND n1 < n2 AND n2 < n3 AND n3 < n4 AND n4 < n5 AND n5 < n6 AND n6 <= 58)
        """,
    ),
    (
        "monthly_expense",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name         TEXT,
        description  TEXT,
        amount       DOUBLE PRECISION,
        period_half  INTEGER,
        period_year  INTEGER,
        period_month INTEGER,
        is_recurring BOOLEAN DEFAULT FALSE,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "pay_period_start_override",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        period_year  INTEGER,
        period_month INTEGER,
        period_half  INTEGER,
        start_date   DATE,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (period_year, period_month, period_half)
        """,
    ),
    (
        "payslip",
        """
        id                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        total                 DOUBLE PRECISION,
        commission            DOUBLE PRECISION,
        reimbursement         DOUBLE PRECISION,
        medical_reimbursement DOUBLE PRECISION,
        others                DOUBLE PRECISION,
        mp2                   DOUBLE PRECISION,
        allowances            DOUBLE PRECISION,
        thirteenth_month      DOUBLE PRECISION,
        basic_salary          DOUBLE PRECISION,
        period_year           INTEGER,
        period_month          INTEGER,
        period_half           INTEGER,
        notes                 TEXT,
        withholding_tax       DOUBLE PRECISION,
        sss_contribution      DOUBLE PRECISION,
        philhealth            DOUBLE PRECISION,
        pag_ibig              DOUBLE PRECISION,
        trust_fund            DOUBLE PRECISION,
        pdf_data              BYTEA,
        created_at            TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP,
        company               TEXT NOT NULL DEFAULT 'Sophos'
        """,
    ),
    (
        # Per-company payslip column visibility (Settings → Companies). The
        # flag columns are exactly db.py's _COMPANY_FLAG_COLUMNS, and each
        # defaults to shown except Trust Fund, which is opt-in.
        "company",
        """
        id                         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                       TEXT NOT NULL,
        sort_order                 INTEGER NOT NULL,
        show_total                 BOOLEAN NOT NULL DEFAULT true,
        show_basic_salary          BOOLEAN NOT NULL DEFAULT true,
        show_commission            BOOLEAN NOT NULL DEFAULT true,
        show_reimbursement         BOOLEAN NOT NULL DEFAULT true,
        show_medical_reimbursement BOOLEAN NOT NULL DEFAULT true,
        show_others                BOOLEAN NOT NULL DEFAULT true,
        show_allowances            BOOLEAN NOT NULL DEFAULT true,
        show_thirteenth_month      BOOLEAN NOT NULL DEFAULT true,
        show_withholding_tax       BOOLEAN NOT NULL DEFAULT true,
        show_sss_contribution      BOOLEAN NOT NULL DEFAULT true,
        show_philhealth            BOOLEAN NOT NULL DEFAULT true,
        show_pag_ibig              BOOLEAN NOT NULL DEFAULT true,
        show_mp2                   BOOLEAN NOT NULL DEFAULT true,
        show_trust_fund            BOOLEAN NOT NULL DEFAULT false,
        created_at                 TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(name)) > 0)
        """,
    ),
    (
        "payslip_default",
        """
        half                  INTEGER NOT NULL,
        period_year           TEXT NOT NULL DEFAULT '',
        period_month          TEXT NOT NULL DEFAULT '',
        total                 TEXT NOT NULL DEFAULT '',
        basic_salary          TEXT NOT NULL DEFAULT '',
        commission            TEXT NOT NULL DEFAULT '',
        reimbursement         TEXT NOT NULL DEFAULT '',
        medical_reimbursement TEXT NOT NULL DEFAULT '',
        others                TEXT NOT NULL DEFAULT '',
        mp2                   TEXT NOT NULL DEFAULT '',
        allowances            TEXT NOT NULL DEFAULT '',
        thirteenth_month      TEXT NOT NULL DEFAULT '',
        notes                 TEXT NOT NULL DEFAULT '',
        withholding_tax       TEXT NOT NULL DEFAULT '',
        sss_contribution      TEXT NOT NULL DEFAULT '',
        philhealth            TEXT NOT NULL DEFAULT '',
        pag_ibig              TEXT NOT NULL DEFAULT '',
        trust_fund            TEXT NOT NULL DEFAULT '',
        updated_at            TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        company               TEXT NOT NULL DEFAULT 'Sophos',
        CHECK (half IN (1, 2)),
        PRIMARY KEY (company, half)
        """,
    ),
    (
        "payslip_default_settings",
        """
        settings_half TEXT NOT NULL DEFAULT 'first',
        company       TEXT PRIMARY KEY DEFAULT 'Sophos',
        CHECK (settings_half IN ('first', 'second'))
        """,
    ),
    (
        "travel_trip",
        """
        id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title           TEXT NOT NULL,
        start_date      DATE NOT NULL,
        end_date        DATE NOT NULL,
        notes           TEXT,
        created_at      TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(title)) > 0),
        CHECK (end_date >= start_date)
        """,
    ),
    (
        "travel_city",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id    INTEGER NOT NULL,
        name       TEXT NOT NULL,
        start_date DATE,
        end_date   DATE,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(name)) > 0)
        """,
    ),
    (
        "travel_accommodation",
        """
        id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id              INTEGER NOT NULL,
        name                 TEXT NOT NULL,
        checkin_date         DATE NOT NULL,
        checkout_date        DATE NOT NULL,
        checkin_time         TIME,
        checkout_time        TIME,
        booking_confirmation TEXT,
        instructions         TEXT,
        location_name        TEXT,
        location_map_url     TEXT,
        notes                TEXT,
        created_at           TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(name)) > 0),
        CHECK (checkout_date >= checkin_date)
        """,
    ),
    (
        "travel_flight",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id        INTEGER NOT NULL,
        flight_number  TEXT NOT NULL,
        flight_date    DATE,
        -- Set only for an overnight/red-eye that lands on a later calendar
        -- date than it departs; NULL means it lands the same day.
        arrival_date   DATE,
        departure_time TIME,
        arrival_time   TIME,
        from_location  TEXT,
        from_map_url   TEXT,
        -- City/country the maps link resolved to, if it was one -- used to
        -- build a "City, Country" calendar title instead of the full name.
        from_city      TEXT,
        from_country   TEXT,
        to_location    TEXT,
        to_map_url     TEXT,
        to_city        TEXT,
        to_country     TEXT,
        notes          TEXT,
        created_at     TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(flight_number)) > 0)
        """,
    ),
    (
        "travel_itinerary",
        """
        id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id          INTEGER NOT NULL,
        item_date        DATE NOT NULL,
        start_time       TIME,
        end_time         TIME,
        activity         TEXT NOT NULL,
        location_name    TEXT,
        location_map_url TEXT,
        notes            TEXT,
        created_at       TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        item_end_date    DATE,
        CHECK (length(trim(activity)) > 0)
        """,
    ),
    (
        "travel_transport",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id        INTEGER NOT NULL,
        -- Ground/water transport leg: bus, train, or ferry. Same shape as
        -- travel_flight, with a mode and an optional (rather than required)
        -- number, since a bus/ferry route is not always known/labeled the
        -- way a flight is.
        mode           TEXT NOT NULL,
        number         TEXT,
        travel_date    DATE,
        -- Set only for an overnight leg that arrives on a later calendar
        -- date than it departs; NULL means it arrives the same day.
        arrival_date   DATE,
        departure_time TIME,
        arrival_time   TIME,
        from_location  TEXT,
        from_map_url   TEXT,
        from_city      TEXT,
        from_country   TEXT,
        to_location    TEXT,
        to_map_url     TEXT,
        to_city        TEXT,
        to_country     TEXT,
        notes          TEXT,
        created_at     TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (mode IN ('bus', 'train', 'ferry'))
        """,
    ),
]


FOREIGN_KEYS = [
    ("credit_card_payment", "credit_card_id", "credit_card", "id", "CASCADE"),
    ("house_payment_entry", "house_payment_id", "house_payment", "id", "CASCADE"),
    ("installment", "credit_card_id", "credit_card", "id", "SET NULL"),
    ("installment_line", "installment_id", "installment", "id", "CASCADE"),
    ("lotto_attempt", "draw_id", "lotto_draw", "id", "CASCADE"),
    ("lotto_draw", "game_id", "lotto_game", "id", "RESTRICT"),
    ("travel_accommodation", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_city", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_flight", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_itinerary", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_transport", "trip_id", "travel_trip", "id", "CASCADE"),
]


INDEXES = [
    # Preserves app_user.username's SQLite COLLATE NOCASE uniqueness.
    "CREATE UNIQUE INDEX idx_app_user_username_lower ON app_user (LOWER(username))",
    "CREATE INDEX idx_blood_pressure_created ON blood_pressure (created_at DESC)",
    # insert_company/update_company rely on a case-insensitive name collision
    # raising IntegrityError, and reorder_companies on sort_order being unique.
    "CREATE UNIQUE INDEX idx_company_name_lower ON company (LOWER(name))",
    "CREATE UNIQUE INDEX idx_company_sort_order ON company (sort_order)",
    "CREATE INDEX idx_credit_card_payment_parent ON credit_card_payment (credit_card_id, payment_date DESC)",
    "CREATE INDEX idx_fixed_expense_period ON fixed_expense (period_year, period_month, period_half, created_at DESC)",
    "CREATE INDEX idx_house_payment_created ON house_payment (created_at DESC)",
    "CREATE INDEX idx_house_payment_name ON house_payment (name)",
    "CREATE INDEX idx_house_payment_entry_parent ON house_payment_entry (house_payment_id, paid_on DESC)",
    "CREATE INDEX idx_installment_created ON installment (created_at DESC)",
    "CREATE INDEX idx_installment_credit_card_id ON installment (credit_card_id)",
    "CREATE INDEX idx_installment_finish_name ON installment (finish_date, name)",
    "CREATE INDEX idx_installment_line_parent ON installment_line (installment_id)",
    "CREATE INDEX idx_lotto_attempt_parent ON lotto_attempt (draw_id, created_at)",
    "CREATE INDEX idx_lotto_draw_game_date ON lotto_draw (game_id, draw_date DESC)",
    "CREATE INDEX idx_monthly_expense_period ON monthly_expense (period_year, period_month, period_half, created_at DESC)",
    "CREATE INDEX idx_payslip_created ON payslip (created_at DESC)",
    "CREATE INDEX idx_payslip_period_sort ON payslip (period_year DESC, period_month DESC, period_half DESC, created_at DESC)",
    "CREATE INDEX idx_travel_accommodation_parent ON travel_accommodation (trip_id, checkin_date, created_at)",
    "CREATE INDEX idx_travel_city_parent ON travel_city (trip_id, sort_order, id)",
    "CREATE INDEX idx_travel_flight_parent ON travel_flight (trip_id, flight_date, created_at)",
    "CREATE INDEX idx_travel_itinerary_parent ON travel_itinerary (trip_id, item_date, start_time, created_at)",
    "CREATE INDEX idx_travel_transport_parent ON travel_transport (trip_id, travel_date, created_at)",
    "CREATE INDEX idx_travel_trip_period ON travel_trip (start_date DESC, id DESC)",
]



# Fixed lookup rows for lotto_game, inserted with explicit ids so they match
# lotto_draw.game_id's DEFAULT 3 (Ultra Lotto 6/58) above.
SEED_LOTTO_GAMES = [
    (1, "Grand Lotto 6/55"),
    (2, "Megalotto 6/45"),
    (3, "Ultra Lotto 6/58"),
    (4, "Superlotto 6/49"),
    (5, "Lotto 6/42"),
]


def table_names() -> list[str]:
    return [name for name, _ in SCHEMA]


def sync_lotto_games(cur: Any) -> None:
    """Insert any SEED_LOTTO_GAMES row the database is missing.

    Runs on every startup (``db.init_schema``), not only on a fresh build: a
    game added to the list afterwards would otherwise be absent from an
    existing database, and the Lotto page lists whatever ``lotto_game`` holds,
    so that game simply would not appear. Rows already present are left
    alone -- both id and name are unique.
    """
    cur.executemany(
        'INSERT INTO "lotto_game" (id, name) VALUES (%s, %s) ON CONFLICT DO NOTHING',
        SEED_LOTTO_GAMES,
    )
    cur.execute(
        "SELECT setval(pg_get_serial_sequence('lotto_game', 'id'), "
        "(SELECT max(id) FROM lotto_game))"
    )


def create_all(cur: Any) -> None:
    """Create every table, foreign key and index on an empty database.

    Tables come first so a foreign key never references a table that does not
    exist yet.
    """
    for name, body in SCHEMA:
        cur.execute(f'CREATE TABLE "{name}" (\n{body}\n)')
    sync_lotto_games(cur)
    for tbl, col, ref_tbl, ref_col, on_delete in FOREIGN_KEYS:
        cur.execute(
            f'ALTER TABLE "{tbl}" ADD CONSTRAINT "fk_{tbl}_{col}" '
            f'FOREIGN KEY ("{col}") REFERENCES "{ref_tbl}" ("{ref_col}") '
            f"ON DELETE {on_delete}"
        )
    for stmt in INDEXES:
        cur.execute(stmt)
